Homework done
fesb-distributed-systems-2024/ASeric00-lab-07 pull request #1
Opened 2024-12-08 20:56 UTC by ASeric00

2024-12-22 15:13 UTC, pkaselj requested changes
Bravo, molim te samo promijeni ovo što sam ti naveo čisto da aplikacija bude funkcionalna

2024-12-22 15:13 UTC, pkaselj commented on ASeric00-lab-07/WeatherStation.cs
> +        public long Id { get; set; }
Molim te promijeni polje Id iz long u int. Izgleda da je problem u .NETu nije lako baš long slati preko JSONa i onda se gube znamenke i ne radi. Nije do tebe, to su glupi tehnički problemi, ja ti dajem neko najlakše rješenje, navodno postoji način za slati long preko JSONa ako napraviš da radi dobit ćeš dodatne bodove.

Ako se odlučiš na prvu opciju, označit ću ti sa [1] gdje sve trebaš napraviti izmjene.

Ako se odlučiš na drugu opciju, pogledaj BigInteger strukturu i [ovaj link](https://www.google.com/search?client=firefox-b-d&q=c%23+net+json+model+long+integer)

2024-12-22 15:13 UTC, pkaselj commented on ASeric00-lab-07/WeatherStation.cs
> +            Id = Random.Shared.NextInt64();
[1]

2024-12-22 15:13 UTC, pkaselj commented on ASeric00-lab-07/Controllers/WeatherController.cs
> +        public IEnumerable<WeatherStation> UpdateAStation([FromRoute] long id, [FromBody] WeatherStation newInfo)
[1]

2024-12-22 15:13 UTC, pkaselj commented on ASeric00-lab-07/Controllers/WeatherController.cs
> +        public IEnumerable<WeatherStation> DeleteAStation([FromRoute] long id)
[1]

2024-12-22 15:13 UTC, pkaselj commented on ASeric00-lab-07/Controllers/WeatherController.cs
> +            return _weatherRepository.WeatherStations;
Ako te zanima što je točno problem, stavi breakpoint na ovu liniju, pogledaj koje Id-jeve imaju objekti u `_weatherRepository.WeatherStations` i onda pogledaj što ti piše u JSONu u HTTP responseu

2024-12-26 10:04 UTC, ASeric00 commented on ASeric00-lab-07/WeatherStation.cs
> +        public long Id { get; set; }
Zahvaljujem na sugestiji. Moram reći kako osobno nisam imao problema s prijenosom long int id-a, koristio sam Postman radi lakše vizualizacije i sve je ok radilo. Internet mi je sugerirao kako označavanje id-a kao long int nije loša praksa, no da je moguće napraviti konverziju u string kako bi se eliminirali mogući problemi. Tako sam i napravio, ako smatrate da postoji bolji način, slobodno predložite ili možda da probam s GuId-om kao i ostale kolege.

2025-01-06 19:13 UTC, pkaselj approved these changes
bravo

2025-01-06 19:13 UTC, merged